"""add server_default in column created_at at users table

Revision ID: 410e0f095bcb
Revises: dc41f2881fd8
Create Date: 2025-01-30 23:12:53.294633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410e0f095bcb'
down_revision: Union[str, None] = 'dc41f2881fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
