"""change server_default to default in column created_at and updated_at at users table

Revision ID: bca52788c814
Revises: 410e0f095bcb
Create Date: 2025-02-01 17:56:22.579105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca52788c814'
down_revision: Union[str, None] = '410e0f095bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
